"""init

Revision ID: c99a96db36db
Revises: 
Create Date: 2026-04-15 17:35:56.365628
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99a96db36db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ARTIST', 'CLIENT', 'ADMIN', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('artist_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('price_text', sa.String(length=255), nullable=True),
    sa.Column('price_category', sa.String(length=64), nullable=True),
    sa.Column('deadline_category', sa.String(length=64), nullable=True),
    sa.Column('contacts_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'HIDDEN', 'MODERATION', name='artist_profile_status', native_enum=False), nullable=False),
    sa.Column('complaints_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('views_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('saves_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['artist_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_profile_id'), 'complaints', ['profile_id'], unique=False)
    op.create_index(op.f('ix_complaints_reporter_user_id'), 'complaints', ['reporter_user_id'], unique=False)
    op.create_table('portfolio_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['artist_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_images_profile_id'), 'portfolio_images', ['profile_id'], unique=False)
    op.create_table('profile_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'SAVE', 'SKIP', 'CONTACT', name='profile_action_type', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['artist_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_actions_client_user_id'), 'profile_actions', ['client_user_id'], unique=False)
    op.create_index(op.f('ix_profile_actions_profile_id'), 'profile_actions', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_actions_profile_id'), table_name='profile_actions')
    op.drop_index(op.f('ix_profile_actions_client_user_id'), table_name='profile_actions')
    op.drop_table('profile_actions')
    op.drop_index(op.f('ix_portfolio_images_profile_id'), table_name='portfolio_images')
    op.drop_table('portfolio_images')
    op.drop_index(op.f('ix_complaints_reporter_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_profile_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_table('artist_profiles')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
