"""add client filters

Revision ID: d10ba1bf1a7a
Revises: 4f0d2f6e6d11
Create Date: 2026-04-16 16:18:23.589137
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10ba1bf1a7a'
down_revision = '4f0d2f6e6d11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
